### ISSUE TITLE
_simData.countyCode always returns null

### ISSUE THREAD

**Issue by mbasa** [osamagamal65/sim_service#1]
For some reason getting the countryCode of the SIM will return null, i.e.:
print("DEBUG countryCode : ${_simData.countyCode}");

**Comment by sanak** [comment]
There is no word `countyCode` in https://github.com/osamagamal65/sim_service/blob/master/android/src/main/java/com/cloudsoft/simservice/SimServicePlugin.java, 
so I think that this is typo of `countryCode` in https://github.com/osamagamal65/sim_service/blob/master/lib/sim_service.dart#L54

**Comment by osamagamal65** [comment]
Fixed this issue on 0.1.0
