### ISSUE TITLE
SWIFT_VERSION Error

### ISSUE THREAD

**Issue by WilkerOliveira** [osamagamal65/sim_service#4]
Hello,

I got this error when trying run the project to iOS.

`sim_service` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Could you please tell me how can I fix it or update the plugin with this correction?

Regards.

**Comment by osamagamal65** [comment]
This plugin only works with Android only, unfortunately.
